#cloud-config
runcmd:
  - |
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
    sysctl vm.swappiness=40
    echo 'vm.swappiness=40' | tee -a /etc/sysctl.conf
